// MyMediaLibrary — mock data

const MML_DATA = {
  totals: {
    elements: 3322,
    folders: 7,
    files: 24866,
    diskTB: 40.0,
    used: 39.7,
    free: 0.3,
    movies: 1238,
    series: 1789,
    anime: 295,
  },
  folders: [
    { label: "Movies",        size: 18.7, items: 1238, color: "var(--chart-1)" },
    { label: "Tv",            size: 17.0, items: 655,  color: "var(--chart-3)" },
    { label: "Anime",         size: 3.2,  items: 60,   color: "var(--chart-4)" },
    { label: "Animation",     size: 0.68, items: 184,  color: "var(--chart-2)" },
    { label: "Anime Movies",  size: 0.28, items: 52,   color: "var(--chart-5)" },
    { label: "Spectacles",    size: 0.15, items: 37,   color: "var(--chart-6)" },
    { label: "Tv Not In Sonarr", size: 0.06, items: 1, color: "var(--chart-7)" },
  ],
  genres: [
    { label: "Thriller", value: 1351, pct: 41 },
    { label: "Action", value: 1270, pct: 38 },
    { label: "Drame", value: 1220, pct: 37 },
    { label: "Science-fiction", value: 820, pct: 25 },
    { label: "Comédie", value: 764, pct: 23 },
    { label: "Aventure", value: 739, pct: 22 },
    { label: "Horreur", value: 631, pct: 19 },
    { label: "Crime", value: 588, pct: 18 },
    { label: "Mystère", value: 487, pct: 15 },
    { label: "Fantastique", value: 439, pct: 13 },
    { label: "Animation", value: 303, pct: 9 },
    { label: "Famille", value: 298, pct: 9 },
  ],
  resolutions: [
    { label: "4K",    value: 351,  color: "var(--chart-2)" },
    { label: "1080p", value: 2341, color: "var(--chart-1)" },
    { label: "720p",  value: 615,  color: "var(--chart-5)" },
    { label: "SD",    value: 14,   color: "var(--chart-7)" },
    { label: "Inconnu", value: 1,  color: "var(--muted-2)" },
  ],
  codecs: [
    { label: "H.264", value: 2490, color: "var(--chart-1)" },
    { label: "H.265", value: 829,  color: "var(--chart-5)" },
    { label: "MPEG-4", value: 2,   color: "var(--chart-6)" },
    { label: "Inconnu", value: 1,  color: "var(--muted-2)" },
  ],
  langues: [
    { label: "MULTI", value: 2221, color: "var(--chart-1)" },
    { label: "VF",    value: 1043, color: "var(--chart-3)" },
    { label: "VO",    value: 32,   color: "var(--chart-4)" },
    { label: "Inconnu", value: 26, color: "var(--muted-2)" },
  ],
  providers: [
    { label: "Netflix",   value: 1360, color: "var(--chart-2)" },
    { label: "Disney+",   value: 380,  color: "var(--chart-3)" },
    { label: "Apple TV",  value: 3,    color: "var(--chart-4)" },
    { label: "Aucun",     value: 1695, color: "var(--muted-2)" },
  ],
  scoreBuckets: [
    { label: "0–20",   value: 0,    color: "var(--danger)" },
    { label: "20–40",  value: 27,   color: "#e07a3a" },
    { label: "40–60",  value: 821,  color: "var(--warn)" },
    { label: "60–80",  value: 2155, color: "#a5c93e" },
    { label: "80–100", value: 319,  color: "var(--ok)" },
  ],
  recos: {
    total: 1720,
    high: 366,
    med: 1354,
    quality: 977,
    space: 492,
    langues: 49,
    series: 150,
    donnees: 52,
  },
  recoItems: [
    { prio: "high", type: "Espace",  title: "11.22.63", year: 2016, score: 60, size: "29.5 GB", res: "1080p", codec: "H.264", audio: "Dolby Digital", lang: "VF", reason: "Fichier 1080p excessivement lourd.", action: "Chercher une version plus légère sans perte visible importante." },
    { prio: "high", type: "Espace",  title: "12 Monkeys", year: 2015, score: 60, size: "127.4 GB", res: "1080p", codec: "H.264", audio: "Dolby Digital", lang: "VF", reason: "Fichier 1080p excessivement lourd.", action: "Chercher une version plus légère sans perte visible importante." },
    { prio: "high", type: "Espace",  title: "30 Coins", year: 2020, score: 66, size: "35.7 GB", res: "1080p", codec: "H.264", audio: "Dolby Digital Plus", lang: "MULTI", reason: "Fichier 1080p excessivement lourd.", action: "Chercher une version plus légère sans perte visible importante." },
    { prio: "high", type: "Langues", title: "50 States of Fright", year: 2020, score: 57, size: "4.2 GB", res: "1080p", codec: "H.264", audio: "AAC", lang: "VO", reason: "Aucune piste audio française détectée.", action: "Chercher une version avec audio français." },
    { prio: "high", type: "Espace",  title: "8 Days", year: 2019, score: 51, size: "15.2 GB", res: "720p", codec: "H.264", audio: "Dolby Digital Plus", lang: "VF", reason: "Fichier 720p excessivement lourd.", action: "Chercher une version plus légère ou remplacer par une version 1080p mieux optimisée." },
    { prio: "high", type: "Espace",  title: "9-1-1", year: 2018, score: 56, size: "114.7 GB", res: "720p", codec: "H.264", audio: "Dolby Digital Plus", lang: "MULTI", reason: "Fichier 720p excessivement lourd.", action: "Chercher une version plus légère ou remplacer par une version 1080p mieux optimisée." },
    { prio: "high", type: "Qualité", title: "9-1-1: Lone Star", year: 2020, score: 56, size: "60.6 GB", res: "720p", codec: "H.264", audio: "Dolby Digital Plus", lang: "MULTI", reason: "Résolution faible (720p).", action: "Remplacer par une version 1080p ou supérieure." },
    { prio: "med",  type: "Séries",  title: "9-1-1: Nashville", year: 2025, score: 51, size: "13.3 GB", res: "720p", codec: "H.264", audio: "Dolby Digital Plus", lang: "VF", reason: "Saison incomplète détectée.", action: "Compléter les épisodes manquants (3 sur 10)." },
    { prio: "med",  type: "Données", title: "A Friend of the Family", year: 2017, score: 60, size: "26.6 GB", res: "1080p", codec: "H.264", audio: "Dolby Digital", lang: "VF", reason: "Métadonnées incomplètes.", action: "Rescanner avec ffprobe pour enrichir les données." },
    { prio: "med",  type: "Qualité", title: "Absentia", year: 2017, score: 71, size: "25.7 GB", res: "1080p", codec: "H.265", audio: "Dolby Digital Plus", lang: "MULTI", reason: "Score moyen — codec récent mais audio basique.", action: "Optionnel — version Dolby Atmos disponible." },
    { prio: "med",  type: "Espace",  title: "Adamas", year: 2022, score: 45, size: "24.8 GB", res: "720p", codec: "H.264", audio: "AAC", lang: "VF", reason: "Fichier 720p excessivement lourd.", action: "Chercher une version plus légère ou remplacer par une version 1080p mieux optimisée." },
    { prio: "med",  type: "Espace",  title: "Aftermath (2016)", year: 2016, score: 53, size: "28.4 GB", res: "720p", codec: "H.264", audio: "DTS", lang: "VF", reason: "Fichier 720p excessivement lourd.", action: "Chercher une version plus légère ou remplacer par une version 1080p mieux optimisée." },
  ],
  recentMedia: [
    { title: "Dune: Part Two",        year: 2024, type: "Movies", res: "4K",    score: 92, provider: "Netflix"  },
    { title: "Shogun",                year: 2024, type: "Tv",     res: "4K",    score: 89, provider: "Disney+"  },
    { title: "The Bear",              year: 2024, type: "Tv",     res: "1080p", score: 84, provider: "Disney+"  },
    { title: "Frieren",               year: 2023, type: "Anime",  res: "1080p", score: 86, provider: null },
    { title: "Oppenheimer",           year: 2023, type: "Movies", res: "4K",    score: 90, provider: "Netflix"  },
    { title: "Severance",             year: 2025, type: "Tv",     res: "4K",    score: 88, provider: "Apple TV" },
    { title: "Spider-Verse",          year: 2023, type: "Movies", res: "1080p", score: 81, provider: "Netflix"  },
    { title: "The Boys",              year: 2024, type: "Tv",     res: "1080p", score: 75, provider: null },
  ],
  activity: [
    { t: "Il y a 12 minutes", text: "Scan automatique terminé",       meta: "3322 éléments • 12 nouveaux • 4 suppressions", icon: "scan" },
    { t: "Il y a 2 heures",   text: "47 nouvelles recommandations",   meta: "12 priorité haute • 35 priorité moyenne", icon: "bulb" },
    { t: "Il y a 5 heures",   text: "Nouveau média ajouté",           meta: "Shogun — Saison 2 • 4K • 12 épisodes", icon: "plus" },
    { t: "Hier, 23:45",       text: "Sauvegarde planifiée terminée",  meta: "Base de données • 124 MB", icon: "shield" },
    { t: "Hier, 04:00",       text: "Scan automatique terminé",       meta: "3310 éléments • 0 changements", icon: "scan" },
  ],
  storageProjection: [
    { month: "Déc",  used: 31.4 },
    { month: "Jan",  used: 33.1 },
    { month: "Fév",  used: 34.8 },
    { month: "Mar",  used: 36.2 },
    { month: "Avr",  used: 38.0 },
    { month: "Mai",  used: 39.7 },
  ],
  detectedFolders: [
    { name: "animation", type: "Films",   active: true },
    { name: "anime",     type: "Séries",  active: true },
    { name: "anime-movies", type: "Films", active: true },
    { name: "books",     type: "Ignorer", active: false },
    { name: "comics",    type: "Ignorer", active: false },
    { name: "mangas",    type: "Ignorer", active: false },
    { name: "movies",    type: "Films",   active: true },
    { name: "special",   type: "Ignorer", active: false },
    { name: "spectacles", type: "Films",  active: true },
    { name: "tv",        type: "Séries",  active: true },
  ],
};

window.MML_DATA = MML_DATA;
