"""Genre name normalisation mapping (raw → canonical, None = exclude)."""

DEFAULT_GENRE_MAPPING: dict[str, str | None] = {
    "Action":          "Action",
    "Adventure":       "Adventure",
    "Animation":       "Animation",
    "Anime":           "Anime",
    "Children":        "Children",
    "Comedy":          "Comedy",
    "Comédie":         "Comedy",
    "Crime":           "Crime",
    "Documentary":     "Documentary",
    "Drama":           "Drama",
    "Family":          "Family",
    "Fantasy":         "Fantasy",
    "Food":            "Food",
    "Game Show":       "Game Show",
    "History":         "History",
    "Horror":          "Horror",
    "Martial Arts":    "Martial Arts",
    "Mini-Series":     None,
    "Music":           "Music",
    "Musical":         "Musical",
    "Mystery":         "Mystery",
    "Reality":         "Reality",
    "Romance":         "Romance",
    "Science Fiction": "Science Fiction",
    "Soap":            "Soap",
    "Sport":           "Sport",
    "Suspense":        "Suspense",
    "TV Movie":        None,
    "Talk Show":       "Talk Show",
    "Thriller":        "Thriller",
    "Travel":          "Travel",
    "War":             "War",
}
