"""Default streaming provider name mappings and logos."""

DEFAULT_PROVIDERS: dict[str, str | None] = {
    'ALLBLK': None,
    'ALLBLK Amazon channel': None,
    'ALLBLK Apple TV channel': None,
    'AMC': None,
    'AMC Channels Amazon Channel': None,
    'AMC Plus Apple TV Channel': None,
    'AMC+': None,
    'AMC+ Amazon Channel': None,
    'AMC+ Roku Premium Channel': None,
    'ARD Plus': None,
    'ARD Plus Amazon channel': None,
    'ARD Plus Apple TV channel': None,
    'ARTE Boutique': None,
    'AXN Black Amazon Channel': None,
    'AXN White Amazon Channel': None,
    'Acontra Plus': None,
    'Acontra Plus Amazon Channel': None,
    'Acorn TV': None,
    'Acorn TV Apple TV': None,
    'AcornTV Amazon Channel': None,
    'Action Max Amazon Channel': None,
    'Adrenalin Amazon channel': None,
    'Adrenalina Pura Amazon channel': None,
    'Adrenalina Pura Apple TV channel': None,
    'Adult Swim': None,
    'Akibapass': None,
    'Allente': None,
    'Allstars Amazon Channel': None,
    'Amasia+ Amazon Channel': None,
    'Amazon Arthaus Channel': None,
    'Amazon Prime Video': 'Prime Video',
    'Amazon Prime Video with Ads': 'Prime Video',
    'Amazon Video': 'Prime Video',
    'Amebatv Amazon Channel': None,
    'Amediateka': None,
    'Angel Studios': None,
    'Animation Digital Network': 'ADN',
    'Animax Amazon Channel': None,
    'Anime Digital Network Amazon Channel': None,
    'Anime Generation Amazon Channel': None,
    'Anime Times Amazon Channel': None,
    'Aniverse Amazon Channel': None,
    'Anni Duemila Amazon Channel': None,
    'Apple TV': 'Apple TV',
    'Apple TV Amazon Channel': 'Apple TV',
    'Apple TV Store': 'Apple TV',
    'Arrow Video Amazon Channel': None,
    'Arthaus+': None,
    'Arthaus+ Apple TV channel': None,
    'Arthouse CNMA Amazon Channel': None,
    'ArthouseCNMA': None,
    'Asia Premium Amazon Channel': None,
    'Asian Drama Channel Amazon Channel': None,
    'AsianCrush': None,
    'Atres Player': None,
    'Atresplayer Amazon Channel': None,
    'BATTLEZONE Amazon Channel': None,
    'BBC America': None,
    'BBC Player Amazon Channel': None,
    'BBC iPlayer': None,
    'BFI Player': None,
    'BFI Player Amazon Channel': None,
    'BFI Player Apple TV Channel': None,
    'BINGE': None,
    'BS10 STAR CHANNEL EX Amazon Channel': None,
    'Be TV Go': None,
    'Beamafilm': None,
    'Belas Artes à La Carte': None,
    'Benshi Amazon Channel': None,
    'Blockbuster': None,
    'Bloodstream': None,
    'Bloody Movies Amazon Channel': None,
    'Booh Amazon Channel': None,
    'Bookmyshow': None,
    'BritBox': None,
    'BritBox Amazon Channel': None,
    'Britbox Apple TV Channel': None,
    'CANAL+': None,
    'CDA Premium': None,
    'CG Collection Amazon channel': None,
    'CG TV STREAMING': None,
    'CHILI': None,
    'CTV': None,
    'Canal VOD': None,
    'Canal+': None,
    'Canal+ Séries': None,
    'Catchplay': None,
    'Channel 4 Plus': None,
    'Channel K Amazon Channel': None,
    'Channel Kyofu Amazon Channel': None,
    'Cindie Amazon Channel': None,
    'Cine+ OCS Amazon Channel': None,
    'CineMember': None,
    'CineMix+ Amazon Channel': None,
    'Cinefil Wow Plus Amazon Channel': None,
    'Cinema of Hearts Amazon Channel': None,
    'Cinemax Amazon Channel': None,
    'Cinemax Apple TV Channel': None,
    'Cineverse': None,
    'Cinobo': None,
    'Cinu': None,
    'Cirkus Amazon Channel': None,
    'Citytvplus': None,
    'Citytvplus Amazon Channel': None,
    'Claro tv+': None,
    'Claro video': None,
    'Club Illico': None,
    'Cohen Media Amazon Channel': None,
    'CosmoGo': None,
    'Crave': None,
    'Crave Amazon Channel': None,
    'Criterion Channel': None,
    'Crunchyroll': 'Crunchyroll',
    'Crunchyroll Amazon Channel': 'Crunchyroll',
    'Cultpix': None,
    'Curiosity Stream': None,
    'CuriosityStream Amazon Channel': None,
    'CuriosityStream Apple TV Channel': None,
    'Curzon Amazon Channel': None,
    'DIRECTV GO': None,
    'Diamond Films Amazon Channel': None,
    'Disaster X Amazon Channel': None,
    'Discovery +': 'Discovery+',
    'Discovery+': 'Discovery+',
    'Discovery+ Amazon Channel': 'Discovery+',
    'Disney Plus': 'Disney+',
    'Disney+': 'Disney+',
    'DocAlliance Films': None,
    'DocPlay': None,
    'DocPlay Amazon Channel': None,
    'Docsville Amazon Channel': None,
    'Doki Amazon Channel': None,
    'Dove Amazon Channel': None,
    'Draken Films': None,
    'EPIC ON': None,
    'Eagle Magic Amazon Channel': None,
    'Eagle No Limits Amazon Channel': None,
    'Echoboom Amazon Channel': None,
    'Edisonline': None,
    'Elisa Viihde': None,
    'FILMO': None,
    'FOD': None,
    'FOD Channel Amazon Channel': None,
    'FOX One Amazon Channel': None,
    'FXNow': None,
    'Fandango At Home': None,
    'Fandor': None,
    'Fandor Amazon Channel': None,
    'Far East Amazon Channel': None,
    'Fear Factory Amazon Channel': None,
    'Fetch TV': None,
    'Film Movement Plus': None,
    'Film Movement Plus Amazon Channel': None,
    'Film Total Amazon Channel': None,
    'Film1': None,
    'FilmBox Live Amazon Channel': None,
    'FilmBox+': None,
    'Filmelier Plus Amazon Channel': None,
    'Filmicca': None,
    'Filmin': None,
    'Filmlegenden Amazon Channel': None,
    'Filmstriben': None,
    'Filmtastic': None,
    'Filmtastic Amazon Channel': None,
    'Filmtastic bei Canal+': None,
    'Fix And Foxi Amazon Channel': None,
    'FlimmerkisteTV Amazon Channel': None,
    'FlixFling': None,
    'FlixOlé': None,
    'FlixOlé Amazon Channel': None,
    'Foxtel Now': None,
    'Franatic Amazon Channel': None,
    'France Channel Amazon Channel': None,
    'France TV Amazon Channel': None,
    'Freeform': None,
    'Freenet meinVOD': None,
    'Full Action Amazon Channel': None,
    'Full Moon Amazon Channel': None,
    'Fuse+ Amazon Channel': None,
    'GEO Television + Wild Amazon Channel': None,
    'GEO Television Amazon Channel': None,
    'Galactic Stream Amazon Channel': None,
    'Globoplay': None,
    'Go3': None,
    'Good Movies Amazon Channel': None,
    'Google Play Movies': None,
    'GuideDoc': None,
    'HBO Max': None,
    'HBO Max Amazon Channel': None,
    'HBO Max on U-Next': None,
    'HISTORY Vault Amazon Channel': None,
    'HISTORY Vault Apple TV Channel': None,
    'HRTi': None,
    'Hallmark TV Amazon Channel': None,
    'Hallmark+ Amazon Channel': None,
    'Hallmark+ Apple TV Channel': None,
    'Hayu Amazon Channel': None,
    'Hi-YAH': None,
    'Hi-YAH Amazon Channel': None,
    'HiDive': None,
    'Hidive Amazon Channel': None,
    'History Vault': None,
    'Hollywood Suite': None,
    'Hollywood Suite Amazon Channel': None,
    'Home of Horror': None,
    'Home of Horror Amazon Channel': None,
    'Hopster Amazon Channel': None,
    'Hulu': 'Hulu',
    'Hungama Play': None,
    'IFC Amazon Channel': None,
    'IFC Films Unlimited Apple TV Channel': None,
    'IFI@Home': None,
    'INA madelen Amazon Channel': None,
    'IROKOTV': None,
    'ITVX Premium': None,
    'Icon Film Amazon Channel': None,
    'Indie Club Amazon Channel': None,
    'IndieFlix': None,
    'IndiePix Unlimited Amazon Channel': None,
    'Infinity Selection Amazon Channel': None,
    'Insomnia Amazon Channel': None,
    'Investigation Discovery': None,
    'Ivi': None,
    'JioHotstar': None,
    'Joyn Plus': None,
    'KADOKAWA channel Amazon Channel': None,
    'KKTV': None,
    'KPN': None,
    'Kabel Eins Classics Amazon Channel': None,
    'Kanopy': None,
    'Kartoon Channel Amazon Channel': None,
    'Kino Film Collection': None,
    'Kinopoisk': None,
    'Kirjastokino': None,
    'Kixi': None,
    'Kixi Select Amazon Channel': None,
    'KlikFilm': None,
    'Kocowa': None,
    'LINE TV': None,
    'LaCinetek': None,
    'Lepsi TV': None,
    'Lifetime': None,
    'Lionsgate Play': None,
    'Lionsgate Play Amazon Channel': None,
    'Lionsgate Play Apple TV Channel': None,
    'Lionsgate+ Amazon Channels': None,
    'Looke': None,
    'Looke Amazon Channel': None,
    'Love and Passion Amazon Channel': None,
    'M6+': None,
    'M6plus Amazon Channel': None,
    'MAX Stream': None,
    'MBS Dougaizm Select Amazon Channel': None,
    'MGM Amazon Channel': None,
    'MGM Plus': None,
    'MGM Plus Amazon Channel': None,
    'MGM Plus Roku Premium Channel': None,
    'MGM+ Amazon Channel': None,
    'MGM+ Apple TV Channel': None,
    'MIDNIGHT FACTORY Amazon Channel': None,
    'MTV Katsomo': None,
    'MUBI': None,
    'MUBI Amazon Channel': None,
    'MYmovies One': None,
    'MZ Choice Amazon Channel': None,
    'Made in Europe Amazon Channel': None,
    'Magenta TV+': None,
    'MagentaTV': None,
    'Magnolia Network Amazon Channel': None,
    'Magnolia Selects Amazon Channel': None,
    'Marquee TV Amazon Channel': None,
    'Mediaset Infinity': None,
    'Mhz Choice': None,
    'Midnight Pulp': None,
    'Midnight Pulp Amazon Channel': None,
    'Molotov TV': None,
    'Monomax': None,
    'Monsters and Nightmares Amazon Channel': None,
    'More TV': None,
    'MovieSphere+ Amazon Channel': None,
    'Moviecult Amazon Channel': None,
    'Moviedome Plus Amazon Channel': None,
    'Movistar Plus+': None,
    'Movistar Plus+ Ficción Total': None,
    'MovistarTV': None,
    'NBC': None,
    'NLZIET': None,
    'NPO Plus': None,
    'Neon TV': None,
    'Netflix': 'Netflix',
    'Netflix Kids': 'Netflix',
    'Netflix Standard with Ads': 'Netflix',
    'Netzkino': None,
    'Netzkino Select Amazon Channel': None,
    'Nexo Plus': None,
    'Nordisk Film+': None,
    'Now TV': None,
    'Now TV Cinema': None,
    'Nuestro Cine MX': None,
    'OSN+': None,
    'OUTtv Amazon Channel': None,
    'OUTtv Apple TV Channel': None,
    'OVID': None,
    'Okko': None,
    'Oldflix': None,
    'Oneplay': None,
    'Orange VOD': None,
    'Otta': None,
    'PBS': None,
    'PBS Masterpiece Amazon Channel': None,
    'Paramount Pictures': None,
    'Paramount Plus': 'Paramount+',
    'Paramount Plus Apple TV Channel': 'Paramount+',
    'Paramount Plus Basic with Ads': 'Paramount+',
    'Paramount Plus Essential': 'Paramount+',
    'Paramount Plus Premium': 'Paramount+',
    'Paramount+ Amazon Channel': 'Paramount+',
    'Paramount+ Roku Premium Channel': 'Paramount+',
    'Pash Amazon Channel': None,
    'Pathé Home': None,
    'Pathé Thuis': None,
    'Peacock Premium': 'Peacock',
    'Peacock Premium Plus': 'Peacock',
    'Philo': None,
    'Pickbox NOW': None,
    'Pilot WP': None,
    'Planet Horror Amazon Channel': None,
    'Player': None,
    'Playkids Learning Amazon Channel': None,
    'Plus GAGA Amazon Channel': None,
    'Plus Shochiku Amazon Channel': None,
    'Pokémon Amazon Channel': None,
    'Polsat Box Go': None,
    'Premier': None,
    'Premiere Max': None,
    'Premiery Canal+': None,
    'Prima Plus': None,
    'ProSieben Fun Amazon Channel': None,
    'Pure Flix': None,
    'Queens club Amazon Channel': None,
    'Queer Cinemab Amazon Channel': None,
    'RTL Crime Amazon Channel': None,
    'RTL+': None,
    'RTL+ Max Amazon Channel': None,
    'Rakuten TV': None,
    'Rakuten Viki': None,
    'Raro Video Amazon Channel': None,
    'Reserva Imovision': None,
    'Reserva Imovision Amazon Channel': None,
    'RetroCrush Amazon Channel': None,
    'Retrocrush': None,
    'Rialto Amazon Channel': None,
    'Ruutu': None,
    'SF Anytime': None,
    'SFR Play': None,
    'STARZPLAY': None,
    'STUDIOCANAL PRESENTS Apple TV Channel': None,
    'Sat.1 emotions Amazon Channel': None,
    'Screambox Amazon Channel': None,
    'ScreenPix Amazon Channel': None,
    'ScreenPix Apple TV Channel': None,
    'Seven Entertainment Amazon Channel': None,
    'Shadowz': None,
    'Shadowz Amazon Channel': None,
    'Shahid VIP': None,
    'ShortsTV Amazon Channel': None,
    'Shout! Factory Amazon Channel': None,
    'ShowMax': None,
    'Shudder': None,
    'Shudder Amazon Channel': None,
    'Shudder Apple TV Channel': None,
    'Silverline Amazon Channel': None,
    'Sky': None,
    'Sky Go': None,
    'Sky Store': None,
    'Sky X': None,
    'SkyShowtime': None,
    'Sony Liv': None,
    'Sony One Amazon Channel': None,
    'Sony Pictures Amazon Channel': None,
    'Sony pictures': None,
    'Sooner': None,
    'Sooner Amazon Channel': None,
    'Spectrum On Demand': None,
    'StackTV Amazon Channel': None,
    'Stan': None,
    'Starz': None,
    'Starz Amazon Channel': None,
    'Starz Apple TV Channel': None,
    'Starz Roku Premium Channel': None,
    'Strim': None,
    'Studiocanal Presents ALLSTARS Amazon Channel': None,
    'Studiocanal Presents Amazon Channel': None,
    'Studiocanal Presents MOVIECULT Amazon Channel': None,
    'Sun Nxt': None,
    'Sundance Now': None,
    'Sundance Now Amazon Channel': None,
    'Sundance Now Apple TV Channel': None,
    'Super Channel Amazon Channel': None,
    'Super Channel Plus': None,
    'Superfresh Amazon Channel': None,
    'TBS': None,
    'TELESA Amazon Channel': None,
    'TELETOON+ Amazon Channel': None,
    'TF1+': None,
    'TFOU Max Amazon Channel': None,
    'TNT': None,
    'TOD': None,
    'TOD TV': None,
    'TV 2': None,
    'TV 2 Play': None,
    'TV+': None,
    'TV2 Skyshowtime': None,
    'TV4 Play': None,
    'TVING': None,
    'TVNZ+': None,
    'TVP': None,
    'Tele2 Play': None,
    'Telecine Amazon Channel': None,
    'Telenet': None,
    'Telia Play': None,
    'Thirteen': None,
    'Thrillbox Amazon Channel': None,
    'Timvision': None,
    'Tivify': None,
    'Toei Animation Channel Amazon Channel': None,
    'Toei On Demand Amazon Channel': None,
    'Toggo': None,
    'TriArt Play': None,
    'U-NEXT': None,
    'UP Faith & Family Amazon Channel': None,
    'UP Faith & Family Apple TV Channel': None,
    'UPC TV': None,
    'USA Network': None,
    'Univer Video': None,
    'Universal+ Amazon Channel': None,
    'Universcine': None,
    'VI movies and tv': None,
    'VIVA by videofutur': None,
    'VIX': None,
    'Verleihshop': None,
    'ViX Premium Amazon Channel': None,
    'Viaplay': None,
    'Viaplay Amazon Channel': None,
    'Vice TV': None,
    'Videobuster': None,
    'Videoland': None,
    'Videoload': None,
    'Vidio': None,
    'Viu': None,
    'Voyo': None,
    'Vrott Amazon Channel': None,
    'WETA+': None,
    'WOW': None,
    'Warriors and Gangsters Amazon Channel': None,
    'Watcha': None,
    'WeTV': None,
    'Wonder Project Amazon Channel': None,
    'Wow Fiction Amazon Channel': None,
    'XLTV Amazon Channel': None,
    'YouTube': 'YouTube',
    'YouTube Premium': 'YouTube',
    'YouTube TV': 'YouTube',
    'ZDF Krimi Amazon Channel': None,
    'ZDF Select Amazon Channel': None,
    'ZDFtivi Amazon channel': None,
    'Zee5': None,
    'Ziggo TV': None,
    'alleskino Amazon Channel': None,
    'blue TV': None,
    'dAnime Amazon Channel': None,
    'filmingo': None,
    'fuboTV': None,
    'iQIYI': None,
    'iWonder Full Amazon channel': None,
    'iciTouTV': None,
    'iflix': None,
    'kino films+ Amazon Channel': None,
    'maxdome Store': None,
    'meJane': None,
    'tru TV': None,
    'wavve': None,
}

DEFAULT_PROVIDER_LOGOS: dict[str, str] = {
    'Netflix': 'netflix.webp',
    'Canal+': 'canalplus.webp',
    'Prime Video': 'primevideo.webp',
    'Disney+': 'disneyplus.webp',
    'Paramount+': 'paramountplus.webp',
    'HBO Max': 'hbomax.webp',
    'Apple TV+': 'appletv.webp',
    'ADN': 'adn.webp',
    'Crunchyroll': 'crunchyroll.webp',
    'Autres': 'other_play.webp',
}
